apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sahil-R/deployments.git'
    path: events
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-events
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

